.TH ICINGA2-USERSYNCD "1" "May 2024" "icinga2-usersyncd 0.1.1" "User Commands"
.SH NAME
icinga2-usersyncd \- a daemon to synchronize ApiUser entries with Host agents on an Icinga 2 instance
.SH SYNOPSIS
.nf
icinga2-usersyncd [-h] [-V] [-v] [-q] [-c CONFIG] [--no-config]
                  [-L URL] [-u USERNAME] [-p PASSWORD] [-C CERT]
                  [-K KEY] [-A CA_CERT] [-Q QUEUE] [-P PREFIX]
                  [-T TEMPLATES] [-f FILTER] [-t DELAY]
.fi
.SH DESCRIPTION
icinga2\-usersyncd is a daemon to synchronize ApiUser entries with
Host agents on an Icinga 2 instance.
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-V\fR, \fB\-\-version\fR
show program's version information and exit
.TP
\fB\-v\fR, \fB\-\-verbose\fR
show more messages
.TP
\fB\-q\fR, \fB\-\-quiet\fR
show less messages
.TP
\fB\-c\fR CONFIG, \fB\-\-config\fR CONFIG
configuration file (the default is
\fI\,/etc/sysconfig/icinga2\-usersyncd\/\fP)
.TP
\fB\-\-no\-config\fR
do not use a configuration file
.TP
\fB\-L\fR URL, \fB\-\-url\fR URL
Icinga 2 API URL
.TP
\fB\-u\fR USERNAME, \fB\-\-username\fR USERNAME
username to authenticate to Icinga 2 API
.TP
\fB\-p\fR PASSWORD, \fB\-\-password\fR PASSWORD
password to authenticate to Icinga 2 API
.TP
\fB\-C\fR CERT, \fB\-\-cert\fR CERT
certificate to authenticate to Icinga 2 API
.TP
\fB\-K\fR KEY, \fB\-\-key\fR KEY
key to authenticate to Icinga 2 API
.TP
\fB\-A\fR CA_CERT, \fB\-\-ca\fR CA_CERT
Icinga 2 API certificate (CA)
.TP
\fB\-Q\fR QUEUE, \fB\-\-queue\fR QUEUE
event queue name to use (the default is either from
the config or 'icinga2\-usersyncd' if omitted)
.TP
\fB\-P\fR PREFIX, \fB\-\-prefix\fR PREFIX
a prefix for ApiUser names (the default is either from
the config or 'host\-' if omitted)
.TP
\fB\-T\fR TEMPLATES, \fB\-\-templates\fR TEMPLATES
a set of templates each created ApiUser should import
(the default is either from the config or [usersync]
if omitted)
.TP
\fB\-f\fR FILTER, \fB\-\-filter\fR FILTER
an optional Host filter string
.TP
\fB\-t\fR DELAY, \fB\-\-delay\fR DELAY
a number of seconds to wait between connection
attempts (the default is either from the config or 1
if omitted)
.TP
\fB\-\-setup\fR
generate certificate for CN "icinga2-usersyncd" and exit
(the certificate is placed in /var/lib/icinga2/certs/)
.PP
.SH BUGS
Report bugs to https://bugzilla.altlinux.org/.
.SH "SEE ALSO"
.BR icinga2 (8)
